// ADDRESS
export const ADD_ADDRESS = 'ADD_ADDRESS';
export const REMOVE_ADDRESS = 'REMOVE_ADDRESS';
export const SEARCH_ADDRESS = 'SEARCH_ADDRESS';
export const NOT_FOUND_ADDRESS = 'NOT_FOUND_ADDRESS';
